/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service and database are up
         * @description Used by the Docker healthcheck. No session needed.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log in
         * @description Sets the HttpOnly `session` cookie (30 days) and returns the profile. A wrong password
         *     and an unknown email get the same answer; after 5 failures an email waits 15 minutes
         *     (**429 too_many_attempts** with Retry-After).
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Ends the session. Needs `Content-Type: application/json` (a CSRF guard), body `{}`.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who am I
         * @description The logged-in account; driver fields are null for the admin.
         */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change my timezone
         * @description A driver changes only `timezone`; any other field is **403 admin_managed_fields**.
         */
        patch: operations["update_me_api_v1_me_patch"];
        trace?: never;
    };
    "/api/v1/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Shifts of a date
         * @description Shifts that started on `work_date`, each with its summary.
         */
        get: operations["list_shifts_api_v1_shifts_get"];
        put?: never;
        /**
         * Start a shift, or enter a past one
         * @description An empty body starts a shift now. With `started_at` only, a shift starts then; with
         *     `ended_at` too, a finished past shift is entered.
         *
         *     At most 24 hours long, at most 7 days back, never in the future. One open shift at a
         *     time (**409 shift_already_open**); shifts never overlap (**409 shift_overlap**).
         */
        post: operations["start_shift_api_v1_shifts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shifts/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The open shift
         * @description The shift that is still open, or null.
         */
        get: operations["current_shift_api_v1_shifts_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/shifts/{shift_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A shift with its trips */
        get: operations["get_shift_api_v1_shifts__shift_id__get"];
        put?: never;
        post?: never;
        /** Delete a shift and its trips */
        delete: operations["delete_shift_api_v1_shifts__shift_id__delete"];
        options?: never;
        head?: never;
        /**
         * Change a shift
         * @description Only the fields sent change. The trips must stay inside; `ended_at: null` reopens the
         *     latest shift. 409 shift_locked once it ended more than 7 days ago.
         */
        patch: operations["update_shift_api_v1_shifts__shift_id__patch"];
        trace?: never;
    };
    "/api/v1/shifts/{shift_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close the open shift
         * @description Ends the shift now or at `ended_at`, not before its last trip. A forgotten shift can
         *     always be closed, with an end within 24 hours of its start.
         */
        post: operations["close_shift_api_v1_shifts__shift_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dates with shifts
         * @description Every work date with at least one shift, with its trip count and take-home: the calendar.
         */
        get: operations["list_days_api_v1_days_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trips of a date
         * @description Trips of the shifts that started on `work_date`, a night shift's trips after midnight included.
         */
        get: operations["list_trips_api_v1_trips_get"];
        put?: never;
        /**
         * Add a trip
         * @description Adds a trip to one of the driver's shifts, inside its start and end.
         *
         *     Idempotent by `id`: a retried request returns **200** with the stored trip. The same `id`
         *     with different data is **409 trip_conflict**; a time that overlaps another trip is
         *     **409 trip_overlap**. With a commission percent set by the admin, the server computes
         *     `commission_amount`. A shift that ended more than 7 days ago no longer takes trips.
         */
        post: operations["add_trip_api_v1_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Totals of a date
         * @description Revenue, commission, take-home and the cash/card split of the date's shifts.
         */
        get: operations["day_summary_api_v1_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a trip */
        delete: operations["delete_trip_api_v1_trips__trip_id__delete"];
        options?: never;
        head?: never;
        /**
         * Change a trip
         * @description Only the fields sent change; the same rules as adding apply. A new fare recomputes the
         *     commission with the percent stored with the trip. 409 shift_locked after 7 days.
         */
        patch: operations["update_trip_api_v1_trips__trip_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Drivers with their totals */
        get: operations["list_drivers_api_v1_admin_drivers_get"];
        put?: never;
        /** Create a driver */
        post: operations["create_driver_api_v1_admin_drivers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/drivers/{driver_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A driver */
        get: operations["get_driver_api_v1_admin_drivers__driver_id__get"];
        put?: never;
        post?: never;
        /** Delete a driver with all their data */
        delete: operations["delete_driver_api_v1_admin_drivers__driver_id__delete"];
        options?: never;
        head?: never;
        /** Change a driver */
        patch: operations["update_driver_api_v1_admin_drivers__driver_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/drivers/{driver_id}/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The driver's dates with shifts */
        get: operations["driver_days_api_v1_admin_drivers__driver_id__days_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/drivers/{driver_id}/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The driver's trips of a date */
        get: operations["driver_trips_api_v1_admin_drivers__driver_id__trips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/drivers/{driver_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The driver's totals of a date */
        get: operations["driver_summary_api_v1_admin_drivers__driver_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/drivers/{driver_id}/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The driver's shifts of a date */
        get: operations["driver_shifts_api_v1_admin_drivers__driver_id__shifts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/drivers/{driver_id}/shifts/{shift_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A shift of the driver */
        get: operations["driver_shift_api_v1_admin_drivers__driver_id__shifts__shift_id__get"];
        put?: never;
        post?: never;
        /** Delete a shift and its trips */
        delete: operations["delete_driver_shift_api_v1_admin_drivers__driver_id__shifts__shift_id__delete"];
        options?: never;
        head?: never;
        /** Correct a shift, without the 7-day limit */
        patch: operations["update_driver_shift_api_v1_admin_drivers__driver_id__shifts__shift_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/drivers/{driver_id}/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a trip */
        delete: operations["delete_driver_trip_api_v1_admin_drivers__driver_id__trips__trip_id__delete"];
        options?: never;
        head?: never;
        /** Correct a trip, without the 7-day limit */
        patch: operations["update_driver_trip_api_v1_admin_drivers__driver_id__trips__trip_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DayInfo
         * @description A work date with at least one shift, for the calendar.
         */
        DayInfo: {
            /**
             * Work Date
             * Format: date
             */
            work_date: string;
            /** Trips Count */
            trips_count: number;
            /** Net Income */
            net_income: number;
        };
        /**
         * DaySummary
         * @description Totals of all trips in the shifts that started on this work date.
         */
        DaySummary: {
            /** Trips Count */
            trips_count: number;
            /**
             * Revenue
             * @description Sum of fares, whole KZT
             */
            revenue: number;
            /** Commission Total */
            commission_total: number;
            /**
             * Net Income
             * @description Take-home: revenue minus commission_total
             */
            net_income: number;
            cash: components["schemas"]["PaymentTotals"];
            card: components["schemas"]["PaymentTotals"];
            /**
             * Work Date
             * Format: date
             */
            work_date: string;
            /** Shifts Count */
            shifts_count: number;
        };
        /** DriverCreate */
        DriverCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /**
             * Password
             * @description 8+ characters with a letter and a digit, not the email
             */
            password: string;
            /** Full Name */
            full_name: string;
            /**
             * Car Model
             * @default
             */
            car_model: string;
            /**
             * Car Plate
             * @description Kazakhstan plate, e.g. 123 ABC 02
             */
            car_plate?: string | null;
            /**
             * Timezone
             * @default Asia/Almaty
             */
            timezone: string;
            /** Commission Percent */
            commission_percent?: number | null;
        };
        /**
         * DriverInfo
         * @description A driver as the admin sees them: profile plus totals.
         */
        DriverInfo: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            role: components["schemas"]["Role"];
            /** Full Name */
            full_name: string;
            /** Car Model */
            car_model: string;
            /**
             * Car Plate
             * @description Normalized, e.g. "123ABC02"
             */
            car_plate?: string | null;
            /** Timezone */
            timezone: string;
            /**
             * Commission Percent
             * @description Set by the admin; null: the driver enters each commission
             */
            commission_percent?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Trips Count */
            trips_count: number;
            /** Revenue */
            revenue: number;
            /** Net Income */
            net_income: number;
            /**
             * Last Work Date
             * @description The latest date with a trip
             */
            last_work_date: string | null;
        };
        /**
         * DriverUpdate
         * @description Only the fields that were sent are changed.
         */
        DriverUpdate: {
            /** Full Name */
            full_name?: string | null;
            /** Car Model */
            car_model?: string | null;
            /**
             * Car Plate
             * @description null removes the plate
             */
            car_plate?: string | null;
            /** Timezone */
            timezone?: string | null;
            /**
             * Commission Percent
             * @description null: the driver enters it
             */
            commission_percent?: number | null;
            /**
             * Password
             * @description Ends all of the driver's sessions
             */
            password?: string | null;
        };
        /**
         * ErrorBody
         * @description Every 4xx and 5xx response. The rejected input itself is never echoed.
         * @example {
         *       "error": {
         *         "code": "validation_error",
         *         "ctx": {},
         *         "fields": [
         *           {
         *             "code": "greater_than",
         *             "ctx": {
         *               "gt": 0
         *             },
         *             "field": "fare",
         *             "message": "…"
         *           }
         *         ],
         *         "message": "Some fields are invalid"
         *       }
         *     }
         */
        ErrorBody: {
            error: components["schemas"]["ErrorDetail"];
        };
        /** ErrorDetail */
        ErrorDetail: {
            /**
             * Code
             * @description Stable code: validation_error, shift_locked, trip_overlap, …
             */
            code: string;
            /** Message */
            message: string;
            /**
             * Fields
             * @description Every invalid field of a 422, all at once
             */
            fields: components["schemas"]["FieldError"][];
            /** Ctx */
            ctx: {
                [key: string]: unknown;
            };
        };
        /** FieldError */
        FieldError: {
            /**
             * Field
             * @description The request field, e.g. ended_at; null for the body as a whole
             */
            field: string | null;
            /**
             * Code
             * @description Stable, e.g. end_before_start; clients translate it
             */
            code: string;
            /**
             * Message
             * @description English, a fallback for unknown codes
             */
            message: string;
            /**
             * Ctx
             * @description Values for the message, e.g. {'expected': 360}
             */
            ctx: {
                [key: string]: unknown;
            };
        };
        /**
         * LoginIn
         * @example {
         *       "email": "demo@example.com",
         *       "password": "demo12345"
         *     }
         */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * PaymentMethod
         * @enum {string}
         */
        PaymentMethod: "cash" | "card";
        /** PaymentTotals */
        PaymentTotals: {
            /**
             * Trips Count
             * @default 0
             */
            trips_count: number;
            /**
             * Amount
             * @description Sum of fares, whole KZT
             * @default 0
             */
            amount: number;
        };
        /**
         * Profile
         * @description The logged-in account. Driver fields are null for admins: an admin is a
         *     user without a driver profile.
         */
        Profile: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            role: components["schemas"]["Role"];
            /** Full Name */
            full_name?: string | null;
            /** Car Model */
            car_model?: string | null;
            /**
             * Car Plate
             * @description Normalized, e.g. "123ABC02"
             */
            car_plate?: string | null;
            /**
             * Timezone
             * @description IANA name, e.g. Asia/Almaty
             */
            timezone?: string | null;
            /**
             * Commission Percent
             * @description Set by the admin; null: the driver enters each commission
             */
            commission_percent?: number | null;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "driver" | "admin";
        /** Shift */
        Shift: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Ended At
             * @description null while the shift is open
             */
            ended_at: string | null;
            status: components["schemas"]["ShiftStatus"];
            /**
             * Work Date
             * Format: date
             * @description The local date the shift started on; its trips count there
             */
            work_date: string;
            /** Note */
            note: string;
            summary: components["schemas"]["ShiftSummary"];
        };
        /** ShiftCloseIn */
        ShiftCloseIn: {
            /**
             * Ended At
             * @description Omitted: now
             */
            ended_at?: string | null;
        };
        /** ShiftDetail */
        ShiftDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Ended At
             * @description null while the shift is open
             */
            ended_at: string | null;
            status: components["schemas"]["ShiftStatus"];
            /**
             * Work Date
             * Format: date
             * @description The local date the shift started on; its trips count there
             */
            work_date: string;
            /** Note */
            note: string;
            summary: components["schemas"]["ShiftSummary"];
            /** Trips */
            trips: components["schemas"]["Trip"][];
        };
        /**
         * ShiftPatch
         * @description Changes to a shift; omitted fields keep their values. `ended_at: null` reopens it.
         */
        ShiftPatch: {
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Note */
            note?: string | null;
        };
        /**
         * ShiftStartIn
         * @description Start a shift now (empty body), at a given time, or enter a finished past shift.
         * @example {}
         * @example {
         *       "ended_at": "2026-10-01T18:00:00+05:00",
         *       "note": "Day",
         *       "started_at": "2026-10-01T08:00:00+05:00"
         *     }
         */
        ShiftStartIn: {
            /**
             * Started At
             * @description Omitted: now
             */
            started_at?: string | null;
            /**
             * Ended At
             * @description Given: a finished past shift, at most 24 hours long
             */
            ended_at?: string | null;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * ShiftStatus
         * @enum {string}
         */
        ShiftStatus: "open" | "closed";
        /** ShiftSummary */
        ShiftSummary: {
            /** Trips Count */
            trips_count: number;
            /**
             * Revenue
             * @description Sum of fares, whole KZT
             */
            revenue: number;
            /** Commission Total */
            commission_total: number;
            /**
             * Net Income
             * @description Take-home: revenue minus commission_total
             */
            net_income: number;
            cash: components["schemas"]["PaymentTotals"];
            card: components["schemas"]["PaymentTotals"];
            /**
             * Duration Minutes
             * @description Up to now for an open shift
             */
            duration_minutes: number;
            /**
             * Net Income Per Hour
             * @description null for a shift shorter than a minute
             */
            net_income_per_hour: number | null;
        };
        /**
         * Trip
         * @description A stored trip.
         */
        Trip: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Shift Id
             * Format: uuid
             */
            shift_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Ended At
             * Format: date-time
             */
            ended_at: string;
            /**
             * Fare
             * @description Whole KZT
             */
            fare: number;
            payment_method: components["schemas"]["PaymentMethod"];
            /**
             * Commission Amount
             * @description Whole KZT
             */
            commission_amount: number;
            /**
             * Commission Percent
             * @description The percent the commission was computed with; null if entered by hand
             */
            commission_percent?: number | null;
            /**
             * Net Income
             * @description fare minus commission_amount
             */
            net_income: number;
        };
        /**
         * TripIn
         * @description A trip as the client sends it.
         * @example {
         *       "commission_amount": 360,
         *       "ended_at": "2026-10-01T08:32:00+05:00",
         *       "fare": 2400,
         *       "id": "0192f0a0-3b1c-7d2e-8f40-5a6b7c8d9e0f",
         *       "payment_method": "card",
         *       "shift_id": "0192f09e-1111-7222-8333-444455556666",
         *       "started_at": "2026-10-01T08:10:00+05:00"
         *     }
         */
        TripIn: {
            /**
             * Id
             * @description Generated by the client once per trip, so that a retried request is recognised and not stored twice. Without it the server derives one from the content.
             */
            id?: string | null;
            /**
             * Shift Id
             * Format: uuid
             * @description The driver's shift the trip belongs to
             */
            shift_id: string;
            /**
             * Started At
             * Format: date-time
             * @description With the UTC offset it was recorded in, e.g. 2026-10-01T08:10:00+05:00
             */
            started_at: string;
            /**
             * Ended At
             * Format: date-time
             * @description 1 minute to 6 hours after started_at
             */
            ended_at: string;
            /**
             * Fare
             * @description What the passenger paid, whole KZT
             */
            fare: number;
            payment_method: components["schemas"]["PaymentMethod"];
            /**
             * Commission Amount
             * @description Whole KZT, less than the fare. Omit it when the admin set a commission percent for the driver: the server computes it then.
             */
            commission_amount?: number | null;
        };
        /**
         * TripPatch
         * @description Changes to a stored trip; omitted fields keep their values. The id never changes.
         */
        TripPatch: {
            /**
             * Shift Id
             * @description Move the trip to another of the driver's shifts
             */
            shift_id?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Ended At */
            ended_at?: string | null;
            /** Fare */
            fare?: number | null;
            payment_method?: components["schemas"]["PaymentMethod"] | null;
            /**
             * Commission Amount
             * @description Only for trips without a commission percent
             */
            commission_amount?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description The database is unreachable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Expected application/json */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_me_api_v1_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "timezone": "Asia/Almaty"
                 *     }
                 */
                "application/json": {
                    /** Timezone */
                    timezone: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_shifts_api_v1_shifts_get: {
        parameters: {
            query: {
                /** @description A local date */
                work_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"][];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    start_shift_api_v1_shifts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftStartIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Clashes with the current state (see error.code) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    current_shift_api_v1_shifts_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"] | null;
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_shift_api_v1_shifts__shift_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftDetail"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_shift_api_v1_shifts__shift_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Clashes with the current state (see error.code) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_shift_api_v1_shifts__shift_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Clashes with the current state (see error.code) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    close_shift_api_v1_shifts__shift_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftCloseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Clashes with the current state (see error.code) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_days_api_v1_days_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayInfo"][];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_trips_api_v1_trips_get: {
        parameters: {
            query: {
                /** @description A local date: the shifts that started on it */
                work_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"][];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    add_trip_api_v1_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripIn"];
            };
        };
        responses: {
            /** @description The same trip again: the stored one, nothing added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Clashes with the current state (see error.code) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    day_summary_api_v1_summary_get: {
        parameters: {
            query: {
                /** @description A local date: the shifts that started on it */
                work_date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySummary"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_trip_api_v1_trips__trip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Clashes with the current state (see error.code) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_trip_api_v1_trips__trip_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Clashes with the current state (see error.code) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_drivers_api_v1_admin_drivers_get: {
        parameters: {
            query?: {
                /** @description Search by name, email, car model or plate */
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverInfo"][];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_driver_api_v1_admin_drivers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverInfo"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Clashes with the current state (see error.code) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_driver_api_v1_admin_drivers__driver_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverInfo"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_driver_api_v1_admin_drivers__driver_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_driver_api_v1_admin_drivers__driver_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverInfo"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Clashes with the current state (see error.code) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    driver_days_api_v1_admin_drivers__driver_id__days_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayInfo"][];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    driver_trips_api_v1_admin_drivers__driver_id__trips_get: {
        parameters: {
            query: {
                /** @description A local date: the shifts that started on it */
                work_date: string;
            };
            header?: never;
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"][];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    driver_summary_api_v1_admin_drivers__driver_id__summary_get: {
        parameters: {
            query: {
                /** @description A local date: the shifts that started on it */
                work_date: string;
            };
            header?: never;
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySummary"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    driver_shifts_api_v1_admin_drivers__driver_id__shifts_get: {
        parameters: {
            query: {
                /** @description A local date: the shifts that started on it */
                work_date: string;
            };
            header?: never;
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"][];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    driver_shift_api_v1_admin_drivers__driver_id__shifts__shift_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_id: string;
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftDetail"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_driver_shift_api_v1_admin_drivers__driver_id__shifts__shift_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_id: string;
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_driver_shift_api_v1_admin_drivers__driver_id__shifts__shift_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_id: string;
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Clashes with the current state (see error.code) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_driver_trip_api_v1_admin_drivers__driver_id__trips__trip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_driver_trip_api_v1_admin_drivers__driver_id__trips__trip_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description No session, or it expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description The account's role may not do this */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Clashes with the current state (see error.code) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Invalid fields: error.fields lists all of them */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Too many requests; see the Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
