/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + database check, used by the Docker healthcheck.
         */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Me */
        patch: operations["update_me_api_me_patch"];
        trace?: never;
    };
    "/api/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Shifts
         * @description Shifts that started on this local day, each with its summary.
         */
        get: operations["list_shifts_api_shifts_get"];
        put?: never;
        /** Start Shift */
        post: operations["start_shift_api_shifts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shifts/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current Shift
         * @description The open shift, or null.
         */
        get: operations["current_shift_api_shifts_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shifts/{shift_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Shift */
        get: operations["get_shift_api_shifts__shift_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Shift
         * @description Deletes the shift together with its trips.
         */
        delete: operations["delete_shift_api_shifts__shift_id__delete"];
        options?: never;
        head?: never;
        /** Update Shift */
        patch: operations["update_shift_api_shifts__shift_id__patch"];
        trace?: never;
    };
    "/api/shifts/{shift_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Shift */
        post: operations["close_shift_api_shifts__shift_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Days */
        get: operations["list_days_api_days_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["list_trips_api_trips_get"];
        put?: never;
        /** Add Trip */
        post: operations["add_trip_api_trips_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Day Summary */
        get: operations["day_summary_api_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Trip */
        delete: operations["delete_trip_api_trips__trip_id__delete"];
        options?: never;
        head?: never;
        /** Update Trip */
        patch: operations["update_trip_api_trips__trip_id__patch"];
        trace?: never;
    };
    "/api/admin/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Drivers */
        get: operations["list_drivers_api_admin_drivers_get"];
        put?: never;
        /** Create Driver */
        post: operations["create_driver_api_admin_drivers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/drivers/{driver_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Driver */
        get: operations["get_driver_api_admin_drivers__driver_id__get"];
        put?: never;
        post?: never;
        /** Delete Driver */
        delete: operations["delete_driver_api_admin_drivers__driver_id__delete"];
        options?: never;
        head?: never;
        /** Update Driver */
        patch: operations["update_driver_api_admin_drivers__driver_id__patch"];
        trace?: never;
    };
    "/api/admin/drivers/{driver_id}/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Driver Days */
        get: operations["driver_days_api_admin_drivers__driver_id__days_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/drivers/{driver_id}/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Driver Trips */
        get: operations["driver_trips_api_admin_drivers__driver_id__trips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/drivers/{driver_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Driver Summary */
        get: operations["driver_summary_api_admin_drivers__driver_id__summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/drivers/{driver_id}/shifts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Driver Shifts */
        get: operations["driver_shifts_api_admin_drivers__driver_id__shifts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/drivers/{driver_id}/shifts/{shift_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Driver Shift */
        get: operations["driver_shift_api_admin_drivers__driver_id__shifts__shift_id__get"];
        put?: never;
        post?: never;
        /** Delete Driver Shift */
        delete: operations["delete_driver_shift_api_admin_drivers__driver_id__shifts__shift_id__delete"];
        options?: never;
        head?: never;
        /** Update Driver Shift */
        patch: operations["update_driver_shift_api_admin_drivers__driver_id__shifts__shift_id__patch"];
        trace?: never;
    };
    "/api/admin/drivers/{driver_id}/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Driver Trip */
        delete: operations["delete_driver_trip_api_admin_drivers__driver_id__trips__trip_id__delete"];
        options?: never;
        head?: never;
        /** Update Driver Trip */
        patch: operations["update_driver_trip_api_admin_drivers__driver_id__trips__trip_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * DayInfo
         * @description Short per-day entry for the day navigation panel: a day with at least one shift.
         */
        DayInfo: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Count */
            count: number;
            /** Net */
            net: number;
        };
        /**
         * DaySummary
         * @description Totals of all trips in the shifts that started on this local day.
         */
        DaySummary: {
            /** Count */
            count: number;
            /** Revenue */
            revenue: number;
            /** Commission */
            commission: number;
            /** Net */
            net: number;
            cash: components["schemas"]["PaymentBreakdown"];
            card: components["schemas"]["PaymentBreakdown"];
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Shifts */
            shifts: number;
        };
        /** DriverCreate */
        DriverCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Name */
            name: string;
            /**
             * Car Model
             * @default
             */
            car_model: string;
            /** Car Plate */
            car_plate?: string | null;
            /**
             * Default Tz
             * @default Asia/Almaty
             */
            default_tz: string;
            /** Default Commission Pct */
            default_commission_pct?: number | null;
        };
        /**
         * DriverInfo
         * @description A driver as the admin sees them: profile plus totals.
         */
        DriverInfo: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            role: components["schemas"]["Role"];
            /** Name */
            name: string;
            /** Car Model */
            car_model: string;
            /** Car Plate */
            car_plate?: string | null;
            /** Default Tz */
            default_tz: string;
            /** Default Commission Pct */
            default_commission_pct?: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Trips Count */
            trips_count: number;
            /** Revenue */
            revenue: number;
            /** Net */
            net: number;
            /** Last Trip Day */
            last_trip_day: string | null;
        };
        /**
         * DriverUpdate
         * @description PATCH /api/admin/drivers/{id}: only the fields that were sent are changed.
         */
        DriverUpdate: {
            /** Name */
            name?: string | null;
            /** Car Model */
            car_model?: string | null;
            /** Car Plate */
            car_plate?: string | null;
            /** Default Tz */
            default_tz?: string | null;
            /** Default Commission Pct */
            default_commission_pct?: number | null;
            /** Password */
            password?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginIn */
        LoginIn: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** PaymentBreakdown */
        PaymentBreakdown: {
            /**
             * Count
             * @default 0
             */
            count: number;
            /**
             * Amount
             * @default 0
             */
            amount: number;
        };
        /**
         * PaymentMethod
         * @enum {string}
         */
        PaymentMethod: "cash" | "card";
        /**
         * Profile
         * @description The logged-in account. Driver fields are None for admins: an admin is a
         *     user without a driver profile.
         */
        Profile: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            role: components["schemas"]["Role"];
            /** Name */
            name?: string | null;
            /** Car Model */
            car_model?: string | null;
            /** Car Plate */
            car_plate?: string | null;
            /** Default Tz */
            default_tz?: string | null;
            /** Default Commission Pct */
            default_commission_pct?: number | null;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "driver" | "admin";
        /** Shift */
        Shift: {
            /** Id */
            id: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** End */
            end: string | null;
            status: components["schemas"]["ShiftStatus"];
            /**
             * Local Day
             * Format: date
             */
            local_day: string;
            /** Note */
            note: string;
            summary: components["schemas"]["ShiftSummary"];
        };
        /** ShiftCloseIn */
        ShiftCloseIn: {
            /** End */
            end?: string | null;
        };
        /** ShiftDetail */
        ShiftDetail: {
            /** Id */
            id: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** End */
            end: string | null;
            status: components["schemas"]["ShiftStatus"];
            /**
             * Local Day
             * Format: date
             */
            local_day: string;
            /** Note */
            note: string;
            summary: components["schemas"]["ShiftSummary"];
            /** Trips */
            trips: components["schemas"]["Trip"][];
        };
        /**
         * ShiftPatch
         * @description Changes to a shift; omitted fields keep their values. `end: null` reopens it.
         */
        ShiftPatch: {
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
            /** Note */
            note?: string | null;
        };
        /**
         * ShiftStartIn
         * @description Start a shift now (no fields), at a given time, or enter a past shift (start + end).
         */
        ShiftStartIn: {
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
            /**
             * Note
             * @default
             */
            note: string;
        };
        /**
         * ShiftStatus
         * @enum {string}
         */
        ShiftStatus: "open" | "closed";
        /** ShiftSummary */
        ShiftSummary: {
            /** Count */
            count: number;
            /** Revenue */
            revenue: number;
            /** Commission */
            commission: number;
            /** Net */
            net: number;
            cash: components["schemas"]["PaymentBreakdown"];
            card: components["schemas"]["PaymentBreakdown"];
            /** Duration Min */
            duration_min: number;
            /** Net Per Hour */
            net_per_hour: number | null;
        };
        /**
         * Trip
         * @description A stored trip.
         */
        Trip: {
            /** Id */
            id: string;
            /** Shift Id */
            shift_id: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Amount */
            amount: number;
            payment: components["schemas"]["PaymentMethod"];
            /** Commission */
            commission: number;
            /** Commission Pct */
            commission_pct?: number | null;
        };
        /**
         * TripIn
         * @description Trip as sent by a client. The id is optional.
         */
        TripIn: {
            /** Id */
            id?: string | null;
            /** Shift Id */
            shift_id: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /**
             * Amount
             * @description Trip amount, KZT
             */
            amount: number;
            payment: components["schemas"]["PaymentMethod"];
            /**
             * Commission
             * @description Commission, KZT
             */
            commission?: number | null;
        };
        /**
         * TripPatch
         * @description Changes to a stored trip; omitted fields keep their values. The id never changes.
         */
        TripPatch: {
            /** Shift Id */
            shift_id?: number | null;
            /** Start */
            start?: string | null;
            /** End */
            end?: string | null;
            /** Amount */
            amount?: number | null;
            payment?: components["schemas"]["PaymentMethod"] | null;
            /** Commission */
            commission?: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
        };
    };
    update_me_api_me_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Profile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_shifts_api_shifts_get: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_shift_api_shifts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftStartIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_shift_api_shifts_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"] | null;
                };
            };
        };
    };
    get_shift_api_shifts__shift_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_shift_api_shifts__shift_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_shift_api_shifts__shift_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_shift_api_shifts__shift_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftCloseIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_days_api_days_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayInfo"][];
                };
            };
        };
    };
    list_trips_api_trips_get: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_trip_api_trips_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    day_summary_api_summary_get: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_trip_api_trips__trip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_trip_api_trips__trip_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drivers_api_admin_drivers_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_driver_api_admin_drivers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_driver_api_admin_drivers__driver_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driver_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_driver_api_admin_drivers__driver_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driver_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_driver_api_admin_drivers__driver_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driver_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DriverUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverInfo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    driver_days_api_admin_drivers__driver_id__days_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                driver_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DayInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    driver_trips_api_admin_drivers__driver_id__trips_get: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path: {
                driver_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    driver_summary_api_admin_drivers__driver_id__summary_get: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path: {
                driver_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DaySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    driver_shifts_api_admin_drivers__driver_id__shifts_get: {
        parameters: {
            query: {
                date: string;
            };
            header?: never;
            path: {
                driver_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    driver_shift_api_admin_drivers__driver_id__shifts__shift_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_id: number;
                driver_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShiftDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_driver_shift_api_admin_drivers__driver_id__shifts__shift_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_id: number;
                driver_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_driver_shift_api_admin_drivers__driver_id__shifts__shift_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                shift_id: number;
                driver_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShiftPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Shift"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_driver_trip_api_admin_drivers__driver_id__trips__trip_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                driver_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_driver_trip_api_admin_drivers__driver_id__trips__trip_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: string;
                driver_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TripPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
