-- migrate:up

-- API v1: UUID keys instead of integers, and column names that say what they hold.
-- New ids are generated by the app as time-ordered UUIDv7; the database default
-- (a random v4) is only a fallback. Existing rows get new ids, relations carried over.

-- 1. New keys next to the old ones
ALTER TABLE users ADD COLUMN uid uuid NOT NULL DEFAULT gen_random_uuid();
ALTER TABLE shifts ADD COLUMN uid uuid NOT NULL DEFAULT gen_random_uuid();

ALTER TABLE drivers ADD COLUMN user_uid uuid;
UPDATE drivers d SET user_uid = u.uid FROM users u WHERE u.id = d.user_id;

ALTER TABLE sessions ADD COLUMN user_uid uuid;
UPDATE sessions s SET user_uid = u.uid FROM users u WHERE u.id = s.user_id;

ALTER TABLE shifts ADD COLUMN driver_uid uuid;
UPDATE shifts s SET driver_uid = u.uid FROM users u WHERE u.id = s.driver_id;

ALTER TABLE trips ADD COLUMN uid uuid, ADD COLUMN driver_uid uuid, ADD COLUMN shift_uid uuid;
UPDATE trips t SET driver_uid = u.uid FROM users u WHERE u.id = t.driver_id;
UPDATE trips t SET shift_uid = s.uid FROM shifts s WHERE s.id = t.shift_id;
-- Trip ids were strings chosen by the client: a UUID stays as it is, anything else
-- ("t1", "auto-…") gets a stable UUID derived from the driver and the old id
UPDATE trips SET uid = CASE
    WHEN id ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$' THEN id::uuid
    ELSE md5(driver_id::text || '/' || id)::uuid
END;

-- 2. Everything that refers to the old keys
ALTER TABLE trips
    DROP CONSTRAINT trips_shift_fkey,
    DROP CONSTRAINT trips_driver_id_fkey,
    DROP CONSTRAINT trips_no_overlap,
    DROP CONSTRAINT trips_pkey;
DROP INDEX trips_shift_idx;
ALTER TABLE shifts
    DROP CONSTRAINT shifts_driver_id_fkey,
    DROP CONSTRAINT shifts_id_driver_key,
    DROP CONSTRAINT shifts_no_overlap,
    DROP CONSTRAINT shifts_pkey;
DROP INDEX shifts_one_open_per_driver;
DROP INDEX shifts_driver_day_idx;
ALTER TABLE sessions DROP CONSTRAINT sessions_user_id_fkey;
DROP INDEX sessions_user_idx;
ALTER TABLE drivers DROP CONSTRAINT drivers_user_id_fkey, DROP CONSTRAINT drivers_pkey;
ALTER TABLE users DROP CONSTRAINT users_pkey;

-- 3. The new keys take the old names (dropping a bigserial column drops its sequence)
ALTER TABLE users DROP COLUMN id;
ALTER TABLE users RENAME COLUMN uid TO id;
ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE drivers DROP COLUMN user_id;
ALTER TABLE drivers RENAME COLUMN user_uid TO user_id;
ALTER TABLE drivers ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE drivers ADD CONSTRAINT drivers_pkey PRIMARY KEY (user_id);
ALTER TABLE drivers ADD CONSTRAINT drivers_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE sessions DROP COLUMN user_id;
ALTER TABLE sessions RENAME COLUMN user_uid TO user_id;
ALTER TABLE sessions ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE sessions ADD CONSTRAINT sessions_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
CREATE INDEX sessions_user_idx ON sessions (user_id);

ALTER TABLE shifts DROP COLUMN id, DROP COLUMN driver_id;
ALTER TABLE shifts RENAME COLUMN uid TO id;
ALTER TABLE shifts RENAME COLUMN driver_uid TO driver_id;
ALTER TABLE shifts ALTER COLUMN driver_id SET NOT NULL;
ALTER TABLE shifts RENAME COLUMN local_day TO work_date;
ALTER TABLE shifts RENAME COLUMN start_offset_min TO started_at_offset_minutes;
ALTER TABLE shifts RENAME COLUMN end_offset_min TO ended_at_offset_minutes;
ALTER TABLE shifts ADD CONSTRAINT shifts_pkey PRIMARY KEY (id);
ALTER TABLE shifts ADD CONSTRAINT shifts_driver_id_fkey
    FOREIGN KEY (driver_id) REFERENCES drivers (user_id) ON DELETE CASCADE;
ALTER TABLE shifts ADD CONSTRAINT shifts_id_driver_key UNIQUE (id, driver_id);
ALTER TABLE shifts ADD CONSTRAINT shifts_no_overlap EXCLUDE USING gist (
    driver_id WITH =,
    tstzrange(started_at, coalesce(ended_at, 'infinity'), '[)') WITH &&
);
CREATE UNIQUE INDEX shifts_one_open_per_driver ON shifts (driver_id) WHERE ended_at IS NULL;
CREATE INDEX shifts_driver_date_idx ON shifts (driver_id, work_date, started_at);

ALTER TABLE trips DROP COLUMN id, DROP COLUMN driver_id, DROP COLUMN shift_id;
ALTER TABLE trips RENAME COLUMN uid TO id;
ALTER TABLE trips RENAME COLUMN driver_uid TO driver_id;
ALTER TABLE trips RENAME COLUMN shift_uid TO shift_id;
ALTER TABLE trips ALTER COLUMN id SET NOT NULL;
ALTER TABLE trips ALTER COLUMN driver_id SET NOT NULL;
ALTER TABLE trips ALTER COLUMN shift_id SET NOT NULL;
ALTER TABLE trips RENAME COLUMN start_at TO started_at;
ALTER TABLE trips RENAME COLUMN end_at TO ended_at;
ALTER TABLE trips RENAME COLUMN start_offset_min TO started_at_offset_minutes;
ALTER TABLE trips RENAME COLUMN end_offset_min TO ended_at_offset_minutes;
ALTER TABLE trips RENAME COLUMN amount TO fare;
ALTER TABLE trips RENAME COLUMN payment TO payment_method;
ALTER TABLE trips RENAME COLUMN commission TO commission_amount;
ALTER TABLE trips RENAME COLUMN commission_pct TO commission_percent;
ALTER TABLE trips RENAME CONSTRAINT trips_amount_check TO trips_fare_positive;
ALTER TABLE trips RENAME CONSTRAINT trips_amount_max TO trips_fare_max;
ALTER TABLE trips RENAME CONSTRAINT trips_commission_check TO trips_commission_below_fare;
ALTER TABLE trips RENAME CONSTRAINT trips_commission_pct_check TO trips_commission_percent_range;
ALTER TABLE trips RENAME CONSTRAINT trips_payment_check TO trips_payment_method_check;
-- Per driver: a client generates the id, and another driver's id is none of its business
ALTER TABLE trips ADD CONSTRAINT trips_pkey PRIMARY KEY (driver_id, id);
ALTER TABLE trips ADD CONSTRAINT trips_driver_id_fkey
    FOREIGN KEY (driver_id) REFERENCES drivers (user_id) ON DELETE CASCADE;
ALTER TABLE trips ADD CONSTRAINT trips_shift_fkey
    FOREIGN KEY (shift_id, driver_id) REFERENCES shifts (id, driver_id) ON DELETE CASCADE;
ALTER TABLE trips ADD CONSTRAINT trips_no_overlap EXCLUDE USING gist (
    driver_id WITH =,
    tstzrange(started_at, ended_at, '[)') WITH &&
);
CREATE INDEX trips_shift_idx ON trips (shift_id, started_at);

-- 4. Driver profile names
ALTER TABLE drivers RENAME COLUMN name TO full_name;
ALTER TABLE drivers RENAME COLUMN default_tz TO timezone;
ALTER TABLE drivers RENAME COLUMN default_commission_pct TO commission_percent;
ALTER TABLE drivers RENAME CONSTRAINT drivers_commission_pct_check TO drivers_commission_percent_range;

-- migrate:down

-- Back to integer keys, numbered in creation order, relations carried over. Trip ids
-- come back as text: the original non-UUID strings are not recoverable.

ALTER TABLE drivers RENAME CONSTRAINT drivers_commission_percent_range TO drivers_commission_pct_check;
ALTER TABLE drivers RENAME COLUMN commission_percent TO default_commission_pct;
ALTER TABLE drivers RENAME COLUMN timezone TO default_tz;
ALTER TABLE drivers RENAME COLUMN full_name TO name;

ALTER TABLE trips RENAME CONSTRAINT trips_payment_method_check TO trips_payment_check;
ALTER TABLE trips RENAME CONSTRAINT trips_commission_percent_range TO trips_commission_pct_check;
ALTER TABLE trips RENAME CONSTRAINT trips_commission_below_fare TO trips_commission_check;
ALTER TABLE trips RENAME CONSTRAINT trips_fare_max TO trips_amount_max;
ALTER TABLE trips RENAME CONSTRAINT trips_fare_positive TO trips_amount_check;
ALTER TABLE trips RENAME COLUMN commission_percent TO commission_pct;
ALTER TABLE trips RENAME COLUMN commission_amount TO commission;
ALTER TABLE trips RENAME COLUMN payment_method TO payment;
ALTER TABLE trips RENAME COLUMN fare TO amount;
ALTER TABLE trips RENAME COLUMN ended_at_offset_minutes TO end_offset_min;
ALTER TABLE trips RENAME COLUMN started_at_offset_minutes TO start_offset_min;
ALTER TABLE trips RENAME COLUMN ended_at TO end_at;
ALTER TABLE trips RENAME COLUMN started_at TO start_at;
ALTER TABLE shifts RENAME COLUMN ended_at_offset_minutes TO end_offset_min;
ALTER TABLE shifts RENAME COLUMN started_at_offset_minutes TO start_offset_min;
ALTER TABLE shifts RENAME COLUMN work_date TO local_day;

-- Integer keys
CREATE SEQUENCE users_id_seq;
ALTER TABLE users ADD COLUMN num bigint;
UPDATE users u SET num = r.n
FROM (SELECT id, row_number() OVER (ORDER BY created_at, id) AS n FROM users) r WHERE r.id = u.id;
CREATE SEQUENCE shifts_id_seq;
ALTER TABLE shifts ADD COLUMN num bigint;
UPDATE shifts s SET num = r.n
FROM (SELECT id, row_number() OVER (ORDER BY created_at, id) AS n FROM shifts) r WHERE r.id = s.id;

ALTER TABLE drivers ADD COLUMN user_num bigint;
UPDATE drivers d SET user_num = u.num FROM users u WHERE u.id = d.user_id;
ALTER TABLE sessions ADD COLUMN user_num bigint;
UPDATE sessions s SET user_num = u.num FROM users u WHERE u.id = s.user_id;
ALTER TABLE shifts ADD COLUMN driver_num bigint;
UPDATE shifts s SET driver_num = u.num FROM users u WHERE u.id = s.driver_id;
ALTER TABLE trips ADD COLUMN text_id text, ADD COLUMN driver_num bigint, ADD COLUMN shift_num bigint;
UPDATE trips SET text_id = id::text;
UPDATE trips t SET driver_num = u.num FROM users u WHERE u.id = t.driver_id;
UPDATE trips t SET shift_num = s.num FROM shifts s WHERE s.id = t.shift_id;

DROP INDEX trips_shift_idx;
ALTER TABLE trips
    DROP CONSTRAINT trips_no_overlap,
    DROP CONSTRAINT trips_shift_fkey,
    DROP CONSTRAINT trips_driver_id_fkey,
    DROP CONSTRAINT trips_pkey;
DROP INDEX shifts_driver_date_idx;
DROP INDEX shifts_one_open_per_driver;
ALTER TABLE shifts
    DROP CONSTRAINT shifts_no_overlap,
    DROP CONSTRAINT shifts_id_driver_key,
    DROP CONSTRAINT shifts_driver_id_fkey,
    DROP CONSTRAINT shifts_pkey;
DROP INDEX sessions_user_idx;
ALTER TABLE sessions DROP CONSTRAINT sessions_user_id_fkey;
ALTER TABLE drivers DROP CONSTRAINT drivers_user_id_fkey, DROP CONSTRAINT drivers_pkey;
ALTER TABLE users DROP CONSTRAINT users_pkey;

ALTER TABLE users DROP COLUMN id;
ALTER TABLE users RENAME COLUMN num TO id;
ALTER TABLE users ALTER COLUMN id SET NOT NULL;
ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_id_seq');
ALTER SEQUENCE users_id_seq OWNED BY users.id;
SELECT setval('users_id_seq', coalesce((SELECT max(id) FROM users), 0) + 1, false);
ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE drivers DROP COLUMN user_id;
ALTER TABLE drivers RENAME COLUMN user_num TO user_id;
ALTER TABLE drivers ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE drivers ADD CONSTRAINT drivers_pkey PRIMARY KEY (user_id);
ALTER TABLE drivers ADD CONSTRAINT drivers_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

ALTER TABLE sessions DROP COLUMN user_id;
ALTER TABLE sessions RENAME COLUMN user_num TO user_id;
ALTER TABLE sessions ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE sessions ADD CONSTRAINT sessions_user_id_fkey
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;
CREATE INDEX sessions_user_idx ON sessions (user_id);

ALTER TABLE shifts DROP COLUMN id, DROP COLUMN driver_id;
ALTER TABLE shifts RENAME COLUMN num TO id;
ALTER TABLE shifts RENAME COLUMN driver_num TO driver_id;
ALTER TABLE shifts ALTER COLUMN id SET NOT NULL;
ALTER TABLE shifts ALTER COLUMN driver_id SET NOT NULL;
ALTER TABLE shifts ALTER COLUMN id SET DEFAULT nextval('shifts_id_seq');
ALTER SEQUENCE shifts_id_seq OWNED BY shifts.id;
SELECT setval('shifts_id_seq', coalesce((SELECT max(id) FROM shifts), 0) + 1, false);
ALTER TABLE shifts ADD CONSTRAINT shifts_pkey PRIMARY KEY (id);
ALTER TABLE shifts ADD CONSTRAINT shifts_driver_id_fkey
    FOREIGN KEY (driver_id) REFERENCES drivers (user_id) ON DELETE CASCADE;
ALTER TABLE shifts ADD CONSTRAINT shifts_id_driver_key UNIQUE (id, driver_id);
ALTER TABLE shifts ADD CONSTRAINT shifts_no_overlap EXCLUDE USING gist (
    driver_id WITH =,
    tstzrange(started_at, coalesce(ended_at, 'infinity'), '[)') WITH &&
);
CREATE UNIQUE INDEX shifts_one_open_per_driver ON shifts (driver_id) WHERE ended_at IS NULL;
CREATE INDEX shifts_driver_day_idx ON shifts (driver_id, local_day, started_at);

ALTER TABLE trips DROP COLUMN id, DROP COLUMN driver_id, DROP COLUMN shift_id;
ALTER TABLE trips RENAME COLUMN text_id TO id;
ALTER TABLE trips RENAME COLUMN driver_num TO driver_id;
ALTER TABLE trips RENAME COLUMN shift_num TO shift_id;
ALTER TABLE trips ALTER COLUMN id SET NOT NULL;
ALTER TABLE trips ALTER COLUMN driver_id SET NOT NULL;
ALTER TABLE trips ALTER COLUMN shift_id SET NOT NULL;
ALTER TABLE trips ADD CONSTRAINT trips_pkey PRIMARY KEY (driver_id, id);
ALTER TABLE trips ADD CONSTRAINT trips_driver_id_fkey
    FOREIGN KEY (driver_id) REFERENCES drivers (user_id) ON DELETE CASCADE;
ALTER TABLE trips ADD CONSTRAINT trips_shift_fkey
    FOREIGN KEY (shift_id, driver_id) REFERENCES shifts (id, driver_id) ON DELETE CASCADE;
ALTER TABLE trips ADD CONSTRAINT trips_no_overlap EXCLUDE USING gist (
    driver_id WITH =,
    tstzrange(start_at, end_at, '[)') WITH &&
);
CREATE INDEX trips_shift_idx ON trips (shift_id, start_at);
