from datetime import UTC, date, datetime, timedelta
from uuid import UUID

from pydantic import ConfigDict, Field, ValidationInfo, field_validator
from pydantic_core import PydanticCustomError

from app.core.constants import MAX_FARE, MAX_TRIP_DURATION, MIN_TRIP_DURATION
from app.core.enums import ErrorCode, PaymentMethod
from app.core.ids import content_id
from app.schemas.common import AwareDatetime, ResponseModel, StrictModel

_TIME_HELP = "With the UTC offset it was recorded in, e.g. 2026-10-01T08:10:00+05:00"


class TripIn(StrictModel):
    """A trip as the client sends it."""

    id: UUID | None = Field(
        default=None,
        description="Generated by the client once per trip, so that a retried request is "
        "recognised and not stored twice. Without it the server derives one from the content.",
    )
    shift_id: UUID = Field(description="The driver's shift the trip belongs to")
    started_at: AwareDatetime = Field(description=_TIME_HELP)
    ended_at: AwareDatetime = Field(description="1 minute to 6 hours after started_at")
    fare: int = Field(gt=0, le=MAX_FARE, description="What the passenger paid, whole KZT")
    payment_method: PaymentMethod
    commission_amount: int | None = Field(
        default=None,
        ge=0,
        description="Whole KZT, less than the fare. Omit it when the admin set a commission percent "
        "for the driver: the server computes it then.",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "examples": [
                {
                    "id": "0192f0a0-3b1c-7d2e-8f40-5a6b7c8d9e0f",
                    "shift_id": "0192f09e-1111-7222-8333-444455556666",
                    "started_at": "2026-10-01T08:10:00+05:00",
                    "ended_at": "2026-10-01T08:32:00+05:00",
                    "fare": 2400,
                    "payment_method": "card",
                    "commission_amount": 360,
                }
            ]
        }
    )

    # Cross-field checks are field validators rather than one model validator:
    # a model validator only runs when every field is valid, so the client would
    # see errors one at a time. Here each error is attached to its own field.

    @field_validator("ended_at")
    @classmethod
    def ends_after_start(cls, v: datetime, info: ValidationInfo) -> datetime:
        started_at = info.data.get("started_at")  # absent if it failed validation itself
        if started_at is None:
            return v
        if v <= started_at:
            raise PydanticCustomError(ErrorCode.END_BEFORE_START, "End must be later than start")
        if v - started_at < MIN_TRIP_DURATION:
            raise PydanticCustomError(ErrorCode.TRIP_TOO_SHORT, "A trip lasts at least a minute")
        if v - started_at > MAX_TRIP_DURATION:
            raise PydanticCustomError(
                ErrorCode.TRIP_TOO_LONG,
                "A trip lasts at most {hours} hours",
                {"hours": MAX_TRIP_DURATION // timedelta(hours=1)},
            )
        return v

    @field_validator("commission_amount")
    @classmethod
    def commission_below_fare(cls, v: int | None, info: ValidationInfo) -> int | None:
        fare = info.data.get("fare")
        if v is not None and fare is not None and v >= fare:
            raise PydanticCustomError(
                ErrorCode.COMMISSION_EXCEEDS_FARE, "Commission must be less than the fare"
            )
        return v

    def content_id(self) -> UUID:
        """The id of a trip sent without one: the same content always gives the same id.
        Times are compared in UTC, so the same trip written with another offset matches."""
        return content_id(
            self.shift_id,
            self.started_at.astimezone(UTC).isoformat(),
            self.ended_at.astimezone(UTC).isoformat(),
            self.fare,
            self.payment_method,
            self.commission_amount,
        )


class TripPatch(StrictModel):
    """Changes to a stored trip; omitted fields keep their values. The id never changes."""

    shift_id: UUID | None = Field(default=None, description="Move the trip to another of the driver's shifts")
    started_at: AwareDatetime | None = None
    ended_at: AwareDatetime | None = None
    fare: int | None = Field(default=None, gt=0, le=MAX_FARE)
    payment_method: PaymentMethod | None = None
    commission_amount: int | None = Field(
        default=None, ge=0, description="Only for trips without a commission percent"
    )

    # Validators run only on fields the client sent, so this rejects an explicit null
    # without making the field required. Cross-field rules are checked by the service
    # on the merged trip, since one side of the pair may come from the stored row.
    @field_validator("shift_id", "started_at", "ended_at", "fare", "payment_method", "commission_amount")
    @classmethod
    def not_null(cls, v: object) -> object:
        if v is None:
            raise PydanticCustomError(ErrorCode.NULL_NOT_ALLOWED, "Field cannot be null")
        return v


class Trip(ResponseModel):
    """A stored trip."""

    id: UUID
    shift_id: UUID
    started_at: datetime
    ended_at: datetime
    fare: int = Field(description="Whole KZT")
    payment_method: PaymentMethod
    commission_amount: int = Field(description="Whole KZT")
    commission_percent: float | None = Field(
        default=None, description="The percent the commission was computed with; null if entered by hand"
    )
    net_income: int = Field(description="fare minus commission_amount")


class PaymentTotals(ResponseModel):
    trips_count: int = 0
    amount: int = Field(default=0, description="Sum of fares, whole KZT")


class Totals(ResponseModel):
    trips_count: int
    revenue: int = Field(description="Sum of fares, whole KZT")
    commission_total: int
    net_income: int = Field(description="Take-home: revenue minus commission_total")
    cash: PaymentTotals
    card: PaymentTotals


class DaySummary(Totals):
    """Totals of all trips in the shifts that started on this work date."""

    work_date: date
    shifts_count: int


class DayInfo(ResponseModel):
    """A work date with at least one shift, for the calendar."""

    work_date: date
    trips_count: int
    net_income: int
