from collections.abc import AsyncIterator
from contextlib import asynccontextmanager

from fastapi import FastAPI
from redis.asyncio import Redis

from app.api import errors
from app.api.guards import AuthMiddleware, ThrottleMiddleware
from app.api.middleware import RequestContextMiddleware
from app.api.response_cache import ResponseCacheMiddleware
from app.api.routers import auth, health, me, shifts, trips
from app.api.routers.admin import drivers as admin_drivers
from app.cache.guard import RedisGuard
from app.cache.ratelimit import ResilientRateLimitStore
from app.cache.store import Cache
from app.core.config import get_settings
from app.core.constants import API_V1, API_VERSION, REDIS_TIMEOUT
from app.core.logging import configure_logging
from app.core.ratelimit import LoginLimiter
from app.db.database import Database

API_DESCRIPTION = """
A driver's shift diary: shifts, the trips inside them, and the day's take-home.

**Access.** Log in with `POST /api/v1/auth/login`: it sets an HttpOnly `session` cookie that
the browser then sends by itself. Every other endpoint needs it (401 otherwise). Drivers see
their own diary; the admin manages drivers and corrects their entries.

**Errors.** Every 4xx/5xx has the body `{"error": {"code", "message", "fields", "ctx"}}`.
`code` is stable (see the responses of each endpoint); a 422 lists all invalid fields at once.

**Ids** are UUIDs. A trip's id is generated by the client, so a retried request is not stored
twice. **Times** carry the UTC offset they were recorded in and come back the same way.
**Money** is in whole tenge (KZT).
"""

OPENAPI_TAGS = [
    {"name": "auth", "description": "Log in and out"},
    {"name": "profile", "description": "The logged-in account"},
    {"name": "shifts", "description": "The driver's shifts: start, close, enter past ones, correct"},
    {"name": "trips", "description": "Trips inside shifts, and the per-date views of the diary"},
    {"name": "admin", "description": "Drivers and their diaries, for the admin"},
    {"name": "service", "description": "Health check"},
]


def create_app(db: Database | None = None, redis: Redis | None = None) -> FastAPI:
    """Pass a database (and optionally Redis) in tests; otherwise the app connects to the
    POSTGRES_* database and to REDIS_URL, if set, on startup.

    The app never creates or changes the schema: run `dbmate up` first.
    """

    @asynccontextmanager
    async def lifespan(app: FastAPI) -> AsyncIterator[None]:
        if db is not None:
            yield
            return
        app.state.db = await Database.connect(get_settings().database_url())
        try:
            yield
        finally:
            await app.state.db.close()
            if own_redis is not None:
                await own_redis.aclose()

    # Everything under /api: the frontend's nginx proxies only that prefix
    app = FastAPI(
        title="Driver shift diary",
        version=API_VERSION,
        description=API_DESCRIPTION,
        openapi_tags=OPENAPI_TAGS,
        lifespan=lifespan,
        docs_url=f"{API_V1}/docs",
        redoc_url=None,
        openapi_url=f"{API_V1}/openapi.json",
    )
    if db is not None:
        app.state.db = db
    # Redis for the cache and the rate-limit counters, falling back to this process's
    # memory whenever Redis fails (or when there is none)
    own_redis = None
    if redis is None and db is None and (url := get_settings().redis_url):
        own_redis = redis = Redis.from_url(
            url, socket_timeout=REDIS_TIMEOUT, socket_connect_timeout=REDIS_TIMEOUT
        )
    guard = RedisGuard(enabled=redis is not None)
    app.state.cache = cache = Cache(redis, guard)
    rate_store = ResilientRateLimitStore(redis, guard)
    app.state.login_limiter = LoginLimiter(rate_store)

    errors.install(app)
    # Added inner first: a request passes RequestContext (id, access log), then
    # Throttle (cheap, before any database work), then Auth, then the response cache,
    # then the routers
    app.add_middleware(ResponseCacheMiddleware, cache=cache)
    app.add_middleware(AuthMiddleware)
    app.add_middleware(ThrottleMiddleware, store=rate_store)
    app.add_middleware(RequestContextMiddleware)

    for router in (health.router, auth.router, me.router, shifts.router, trips.router, admin_drivers.router):
        app.include_router(router)

    return app


configure_logging()
app = create_app()
